@startuml
hide circle
/'
esconde el círculo
'/
skinparam classAttributeIconSize 0
/'
le saca la visibilidad a las propiedades y métodos
'/
skinparam monochrome true
/'
lo vuelve blanco y negro
'/
hide members
/'
solo deja el nombre de las clases
'/
left to right direction
/'
genera el uml en columnas (de izquierda a derecha)
'/
skinparam classAttributeIconSize 0
actor "Empleado" as empleado
rectangle MenuInicioSecion{
usecase "Registrar usuario nuevo" as registrar
usecase "Abrir sesión" as abrirSesion
usecase "Cerrar sesión" as cerrarSesion
}

rectangle MenuEmpleado{
usecase "Listar todos los datos accesibles" as listarTodoE
}

empleado --> registrar
empleado --> abrirSesion
empleado --> cerrarSesion
empleado --> listarTodoE

@enduml